title: SuziLog
description: Upload projects

url: http://brianmaierjr.github.com/long-haul
baseurl: /
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: suzishin
   email: suzi619@naver.com

google_analytics: "UA-58263416-1"
